### ISSUE TITLE
json output

### ISSUE THREAD

**Issue by lu3do** [andrewrk/waveform#12]
Hi,
Any change you would add an option to output the waveform as floating points json?

Kind regards,

**Comment by dz0ny** [comment]
https://gist.github.com/dz0ny/10154196 :>

Example with waveform.js:
![zaslonska slika 2014-04-08 18 47 57](https://cloud.githubusercontent.com/assets/239513/2646395/a1a27a96-bf3d-11e3-88ac-043280ef5695.png)

**Comment by andrewrk** [comment]
the project now supports transcoding as well as waveformjs floating point json output.
