### ISSUE TITLE
Undefined reference to `sws_isSupportedEndiannessConversion@LIBSWSCALE_2'

### ISSUE THREAD

**Issue by e10k** [andrewrk/waveform#14]
When compiling with 
`gcc -o waveform main.c -O3 -lgroove -lz -lpng`

I get

`/usr/lib/i386-linux-gnu/libavfilter.so.3: undefined reference to `sws_isSupportedEndiannessConversion@LIBSWSCALE_2'
collect2: ld returned 1 exit status`

It looks like it has to do with libgroove, which I successfully installed from Ubuntu PPA.

Using Ubuntu 12.04. 
Thanks!

**Comment by andrewrk** [comment]
Make sure you have the correct version of the libswscale package installed. It should be version 10. Looks like I didn't lock the version number closely enough in the PPA, I'll take a look at that.

**Comment by andrewrk** [comment]
newest version in PPA should be version locked correctly.
