### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by maddog9486** [andrewrk/waveform#18]
I'm new to Linux (Ubuntu) and can't seem to figure out how to install this, I beleive i have installed the other required items (libgroove, libpng and zlib). Any help would be greatly appreciated. Thanks.

**Comment by maddog9486** [comment]
The "lib" items had clear instructions, but I didn't know how the "make" applied for this waveform piece. Hopefully someone can assist me on this. Thanks.

**Comment by andrewrk** [comment]
what happens if you do this?

```
git clone https://github.com/andrewrk/waveform
cd waveform
make
./waveform
```

Welcome to Linux :-)

**Comment by maddog9486** [comment]
Andrew, thanks. That got it installed. Now I'm assuming this is run from the terminal as I see the options, however, I entered "waveform (input path) (output path)" but nothing happens. Sorry for all the noob questions, try to figure out how to run the commands. The "--" before each command is throwing me off.

**Comment by maddog9486** [comment]
How to use: 
waveform [options] in [--transcode out] [--waveformjs out] [--png out]

What I've entered:
1) waveform /home/Ubuntu/music /home/Ubuntu/pictures
2) waveform scan /home/Ubuntu/music /home/Ubuntu/pictures
3) waveform /home/Ubuntu/music/example1.mp3 /home/Ubuntu/pictures/example1.png
4) waveform /home/Ubuntu/music/example1.mp3 /home/Ubuntu/pictures/example1.png

Obviously those are incorrect, so how do I generate the waveform and secondly how do I set the options for that waveform (colors, size, etc.). If you could mock up an example of what I would type in that would be greatly appreciated.

**Comment by andrewrk** [comment]
Here is an example:

```
waveform /home/Ubuntu/music/example1.mp3 --png /home/Ubuntu/pictures/example1.png
```

`--scan` does not scan for files; rather it scans the single file that you give it to find out the true duration of the audio instead of relying on tags.

Example:

```
waveform --scan /home/Ubuntu/music/example1.mp3 --png /home/Ubuntu/pictures/example1.png
```
