### ISSUE TITLE
Width in samples

### ISSUE THREAD

**Issue by swordsreversed** [andrewrk/waveform#21]
Hi, new to this area, could you explain what 'width in sample' indicates?

[audiowaveform](https://github.com/bbcrd/audiowaveform)  uses

> samples_per_pixel:
> 
> Number of audio samples per waveform minimum/maximum pair

Does it correspond to that? (not even sure if waveformjs outputs pairs). Also what does framecount indidcate?

Sorry for the dumb questions, just pretty confused atm.

**Comment by andrewrk** [comment]
I think it does correspond to that. However waveformjs output does not necessarily imply pixels; it's as if the audio file is resampled to "width in samples" total number of samples, each sample being one waveformjs number. Does that make sense?

**Comment by swordsreversed** [comment]
I think so. Do you know if it is output as pairs? Audiowavform outputs pairs:

> The next stage is to compute the minimum and maximum sample values over groups of N input samples such that each N input samples produces one pair of minimum and maxmimum points in the output.

**Comment by andrewrk** [comment]
No it's only one number per sample. If waveformjs allows pairs then it's changed since last I looked at it.

**Comment by swordsreversed** [comment]
Thanks for that.
