### ISSUE TITLE
Anyway to get this working?

### ISSUE THREAD

**Issue by nickyhajal** [andrewrk/waveform#22]
Seems like this is out of date/no longer supported but is there anyway to get things working on OSX/Ubuntu? Every way I try seems to throw errors of some kind or another but I don't see many other options for waveform generation.

Thanks!

**Comment by chrisn** [comment]
@nickyhajal As an alternative, maybe take a look at [audiowaveform](https://github.com/bbc/audiowaveform)? (I'm the author of that tool, apologies for the self-promotion, just trying to help)

**Comment by nickyhajal** [comment]
@chrisn Thanks for your work on audiowaveform! It worked great!
