### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by russellbarnhart** [andrewrk/waveform#4]
I'm getting an error when i try to compile:

```
main.c: In function ‘main’:
main.c:121:47: warning: integer overflow in expression [-Woverflow]
```

I used the command you specified in the readme:

```
gcc -o waveform main.c -O3 -lsox -lz -lpng
```

I'm running Ubuntu 12.04.1, all the necessary libs installed.

Thanks for all your work. I'm hoping to get a solution thats faster the the 4 seconds i've been getting using avconv and php to generate 1200x200 pngs.

**Comment by andrewrk** [comment]
1) That's just a warning. It's probably still working for you. Is there a ./waveform binary now?

2) I'm also using Ubuntu 12.04 and I'm not getting the warning.

a) Are you sure you're using the latest code? 
b) What is your gcc version?

**Comment by russellbarnhart** [comment]
1) ha. didn't realize that. the binary DOES exist.

Are you sure you're using the latest code?
yeah. just pulled in your latest commit and had another go. same compile warning.

when i execute the binary:

```
./waveform /tmp/source.mp3 /tmp/out.png
```

i get:

```
Segmentation fault (core dumped)
```

What is your gcc version?

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.6/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
```

**Comment by andrewrk** [comment]
Ah there must be a bug when running on 32-bit. Debugging now.
