### ISSUE TITLE
Quality not a recognised argument.

### ISSUE THREAD

**Issue by talkingnews** [andrewrk/waveform#6]
Grabbed the latest version today and compiled it, delighted to see a quality option in the readme.
But "Unrecognized argument: quality" is the result, and I don't even see anything about quality in the C file.
Would be something good for the future, it's very quick, but on hour-long file, this would be a nice option :)

Thanks again for a great bit of code.

**Comment by andrewrk** [comment]
Hey, sorry about that. I recently removed quality when I noticed that the speed difference between the lowest quality and the highest quality was negligible. I forgot to remove it from the README.
